### PR TITLE
Support yuv color streams + jupyter example

### PR DESCRIPTION
**Pull request by papr**
I like that Github [previews notebooks](https://github.com/papr/pyrealsense/blob/master/examples/show_jupyter.ipynb). :)

### CODE REVIEW

**Comment by toinsson** [comment]
good idea to put a jupyter notebook!

Was thinking that the `show_cv2.py` might be better off as simple as possible. So maybe creating another file for the depth pretty printing might be better? Or put a switch in `show_cv2.py` that select which code to run?

What do you think about the versioning, 2.1.1 would be better? We might get to 3.0 rather quick otherwise. And maybe some changelogs is also required to keep track of API changes?

**Comment by papr** [comment]
I agree with all of the above. I think separate examples for color and depth are in order.

**Comment by papr** [comment]
I put more thought into the version number change. I would argue for a change to `2.2` since we break the `ColorStream` API with this PR. We can introduce patch versions (`major.minor.path`) for non-breaking API changes and fixes. Also, one has not necessarily go from `2.9` to `3.0`. Ifit comes to that, I would argue for `2.10` as version.

**Comment by papr** [comment]
@toinsson Would you mind merging this please? :)

**Comment by toinsson** [comment]
Hello, I am off this week with very sporadic internet access.
I'll merge this into dev now, and into master next week.

**Comment by toinsson** [comment]
Thanks for the comments. Agreed on the version numbering ( : ) - did not think that through).

**Pull request merged**
