### PR TITLE
Replace global context with single context per service instance

### PR DESCRIPTION
**Pull request by papr**
Replaces #45 which pushed to `master` instead of `dev`.

Edit: Just noticed that I could have simply changed the target of the old PR instead of making a new one. =/

### CODE REVIEW

**Comment by toinsson** [comment]
yes, sorry for not mentioning this. 
But it looks like you pushed some more code in the end.

It looks very good. I'll just do some testing locally before merging.

**Comment by papr** [comment]
Yeah, I am currently extending it with what we need for our integration. Feel free to criticize the features we are adding.

**Comment by toinsson** [comment]
I was thinking about changing `Stream_Mode` to `StreamMode`, to be more consistent with the naming so far, e.g. stream names and RealsenseError.
What do you think ?

**Comment by papr** [comment]
I agree. I will make a pull request for that.

**Comment by toinsson** [comment]
I am currently updating the `dev` version with documentation change. Can change that also, don't bother.

**Pull request merged**
